eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
instance:
    hostname: localhost
server:
    port: 8081
spring:
    application:
        name: msservice
